### ISSUE TITLE
Add support for Azure Open AI

### ISSUE THREAD

**Issue by talrejanikhil** [swarmzero/swarmzero#13]
Are there plans to support Azure Open AI?

**Comment by ToJen** [comment]
Hello @talrejanikhil, is this something you need? We can support it in an upcoming release. Can you please describe the main use cases around it?

**Comment by talrejanikhil** [comment]
Hi @ToJen , we are using Azure Open AI as an LLM instead of the usual Open AI directly. It would be nice if we can add support for this. Its fairly common in other multi-agent systems to support Azure Open AI as well. Let me know if I can help.
