### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index.llms.azure_openai'

### ISSUE THREAD

**Issue by tonygao79** [swarmzero/swarmzero#15]
When execute "from swarmzero.sdk_context import SDKContext" in python.
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from swarmzero.sdk_context import SDKContext

File ~\swarmzero-main\swarmzero\__init__.py:1
----> 1 from .agent import Agent  # noqa
      2 from .swarm import Swarm

File ~\swarmzero-main\swarmzero\agent.py:30
     28 from swarmzero.llms.ollama import OllamaLLM
     29 from swarmzero.llms.openai import OpenAILLM, OpenAIMultiModalLLM
---> 30 from swarmzero.llms.utils import llm_from_config
     31 from swarmzero.sdk_context import SDKContext
     32 from swarmzero.server.models import ToolInstallRequest

File ~\swarmzero-main\swarmzero\llms\utils\__init__.py:1
----> 1 from .utils import llm_from_config, llm_from_config_without_agent, llm_from_wrapper
      3 __all__ = ["llm_from_config", "llm_from_config_without_agent", "llm_from_wrapper"]

File ~\swarmzero-main\swarmzero\llms\utils\utils.py:18
     16 from llama_index.llms.ollama import Ollama
     17 from llama_index.llms.openai import OpenAI
---> 18 from llama_index.llms.azure_openai import AzureOpenAI
     19 from llama_index.multi_modal_llms.openai import OpenAIMultiModal
     21 from swarmzero.config import Config

ModuleNotFoundError: No module named 'llama_index.llms.azure_openai'.

However, I have install llama_index. I am wondering what reason causes the error. Maybe, I am using the wrong version of llama_index?

**Comment by ToJen** [comment]
Hi @tonygao79, are you installing swarmzero from PyPi or directly from this GitHub repo?

**Comment by tonygao79** [comment]
I am installing swarmzero from Pypi.

**Comment by ToJen** [comment]
Hi @tonygao79, the issue should now be resolved by #16
